eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8880/eureka/
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: 'false '
management:
  security:
    enabled: 'false'
server:
  port: '8881'
spring:
  rabbitmq:
    host: localhost
    port: '5672'